[package]
name = "lucide-gpui"
version = "1.0.0"
edition = "2024"
license = "MIT"
description = "A GPUI-based package for Lucide Icons"
repository = "https://github.com/mateioprea/lucide-gpui"
readme = "README.md"
keywords = ["lucide", "icons", "gpui"]
categories = ["gui"]

[dependencies]
anyhow = "1.0.104"
gpui-kit = "0.6.4"
include_dir = "0.7.4"
